export interface McpServer {
  id: number
  name: string
  display_name: string
  description_en: string
  category: string
  connections: Array<{ type: string; deployment_url: string }>
}

export const BUILTIN_MCP_SERVERS: McpServer[] = [
  { id: 68, name: "global-patent-archive", display_name: "Global Patent Archive", description_en: "Complete access to patent bibliographies, claims, translations, full-text PDFs, and extended data.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/patent/mcp" }] },
  { id: 69, name: "advanced-patent-search", display_name: "Advanced Patent Search", description_en: "Integrates semantic search, reverse image search, classification helpers, and nested querying.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/patent-search/mcp" }] },
  { id: 70, name: "fto-infringement-engine", display_name: "FTO & Infringement Engine", description_en: "Built for FTO and infringement risk mitigation, supporting multi-image comparison and deep semantic/claim analysis.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/infringement/mcp" }] },
  { id: 71, name: "patent-legal-litigation", display_name: "Patent Legal & Litigation", description_en: "Track high-value legal intelligence including global patent litigation, invalidation, UPC status, SEPs.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/patent-legal/mcp" }] },
  { id: 72, name: "patent-snapshot-translator", display_name: "Patent Snapshot & Translator", description_en: "Swiftly extract tech summaries and simple legal status, while providing high-quality machine translation.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/brief/mcp" }] },
  { id: 73, name: "patent-data-aggregation", display_name: "Patent Data Aggregation", description_en: "Offers macro-data aggregation including office statistics, tech lifecycles, 3D maps, and family/citation rankings.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/aggregation/mcp" }] },
  { id: 74, name: "patent-mining-ontology", display_name: "Patent Mining & Ontology", description_en: "Extract value-added data, material ontologies, SEIC classifications, and application domains.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/patent-mining/mcp" }] },
  { id: 75, name: "patent-annuity-manager", display_name: "Patent Annuity Manager", description_en: "Combining legal status tracking with official fee interfaces for annuity management.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/annuity/mcp" }] },
  { id: 76, name: "patent-valuation-model", display_name: "Patent Valuation Model", description_en: "Comprehensive patent valuation integrating legal, tech, market, and economic dimensions.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/patent-value/mcp" }] },
  { id: 77, name: "patent-landscape", display_name: "Patent Landscape", description_en: "Instantly generates advanced business charts like innovation word clouds, strategy radar maps, and citation networks.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/patent-landscape/mcp" }] },
  { id: 79, name: "trademark-search-vision", display_name: "Trademark Search & Vision", description_en: "Delivers powerful trademark field search, reverse image search technology, and detailed trademark profile queries.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/trademark/mcp" }] },
  { id: 80, name: "ip-academy", display_name: "IP Academy", description_en: "Connects to PatSnap Academy resources to easily access professional IP course catalogs.", category: "Ip-Intelligence", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ip/course/mcp" }] },
  { id: 81, name: "bio-ontology-dictionary", display_name: "Bio-Ontology Dictionary", description_en: "Standardizing ontology queries and auto-complete for drugs, targets, diseases.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/bio-dict/mcp" }] },
  { id: 82, name: "compound-sequence-search", display_name: "Compound & Sequence Search", description_en: "Supports advanced search using chemical structures and biological sequences.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/compound-sequence/mcp" }] },
  { id: 83, name: "drug-basic-intelligence", display_name: "Drug Basic Intelligence", description_en: "Retrieval of global drug profiles, approval status, R&D milestones, special reviews.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/drug-basic/mcp" }] },
  { id: 84, name: "clinical-trial-analyzer", display_name: "Clinical Trial Analyzer", description_en: "Deep dive into clinical trial designs, eligibility criteria, patient group results.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/drug-clinical/mcp" }] },
  { id: 85, name: "drug-discovery-mining", display_name: "Drug Discovery & Mining", description_en: "Designed for early-stage R&D, supporting antigen-antibody pairing, affinity search, and deep data mining.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/drug-mining/mcp" }] },
  { id: 86, name: "pharma-pipeline-org-radar", display_name: "Pharma Pipeline & Org Radar", description_en: "Gain insights into pharma companies' core pipeline layouts, research funding, investment dynamics.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/drug-org/mcp" }] },
  { id: 87, name: "pharma-visual-analytics", display_name: "Pharma Visual Analytics", description_en: "Provides advanced visualizations like bullseye chart and R&D milestones, alongside real-time drug intelligence alerts.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/drug-visual/mcp" }] },
  { id: 88, name: "large-molecule-alignment", display_name: "Large Molecule Alignment", description_en: "Professional submission and analysis of large molecule sequence alignments.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/large-molecule/mcp" }] },
  { id: 89, name: "small-molecule-insights", display_name: "Small Molecule Insights", description_en: "Precision search tool for small molecules, instantly penetrating underlying scientific literature.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/small-molecule/mcp" }] },
  { id: 67, name: "pharma-competitive-intelligence", display_name: "Pharma Competitive Intelligence", description_en: "Retrieval of global clinical trials, core drug patents, pharma deals, news, and translational medicine.", category: "Life-Sciences", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/ls/bio-medicine/mcp" }] },
  { id: 96, name: "rims-connector", display_name: "RIMS Connector", description_en: "Tailored for R&D Innovation Management Systems (RIMS), aggregating essential data like patent transfers and licensing.", category: "Finance", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/rnd/rims/mcp" }] },
  { id: 97, name: "scientific-literature-search", display_name: "Scientific Literature Search", description_en: "Crosses the patent barrier to provide scientific literature search, bibliographic info, author affiliations.", category: "R&D-Innovation", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/rnd/literature/mcp" }] },
  { id: 101, name: "auto-report-generator", display_name: "Auto-Report Generator", description_en: "Automatically generates professional-grade research reports, including tech novelty validations.", category: "R&D-Innovation", connections: [{ type: "http", deployment_url: "https://connect.patsnap.com/v1/rnd/zhihuiya-report/mcp" }] },
]
